### PR TITLE
Update the minimum supported nodejs version to v10 and fix bugs

### PR DESCRIPTION
**Pull request by rxliuli**
Note: May contain some bugs, mainly due to two reasons
1. replacing replaceAll with replace
2. replace ? for ||

There are also some non-dangerous replacements
For example, appending the fs-extra module to Promise fs-related operations

---

I created this PR to illustrate how easy it is to support nodejs10. I simply modified a few files. may cause some errors, but I have used this version to generate personal project documents, and it seems that there is no problem at the moment: https://util.liuli.moe/

ref: https://github.com/fliegwerk/fliegdoc/issues/20

### CODE REVIEW

**Comment by rxliuli** [comment]
May need a better way to replace replaceAll, as for ??, may need a utility function?

**Comment by pklaschka** [comment]
First of all: Thank you very much for your contribution. I'll review this asap.

I believe that the replacement for `replaceAll` works alright since, by using a `/g` RegEx pattern (at least from the top of my head, I believe it to be that way) replaces all occurrences, anyway.

With `??`, I'll have to review the occurrences and look into whether falsy values other than `undefined` or `null` are possible in the review process.

**Comment by pklaschka** [comment]
Alright. Results from my initial review (I'll "GitHub-Review" when I've had the chance to test this more thoroughly, this is just the state of my review, as of now 🙂):

- the `?.` in the templates (`variable.eta`, line 14) also won't work in older versions
- `||` instead of `??` in templates causes no problems, according to my initial tests. Falsy literal values, such as `''` actually result in `"''"`, making it no empty string and, thus, not falsy.
- the `package-lock.json` is out of date. **@rxliuli Please run `npm install` to bring it up to date with the changes in `package.json`**

**Comment by rxliuli** [comment]
> Alright. Results from my initial review (I'll "GitHub-Review" when I've had the chance to test this more thoroughly, this is just the state of my review, as of now 🙂):
> 
> * the `?.` in the templates (`variable.eta`, line 14) also won't work in older versions
> * `||` instead of `??` in templates causes no problems, according to my initial tests. Falsy literal values, such as `''` actually result in `"''"`, making it no empty string and, thus, not falsy.
> * the `package-lock.json` is out of date. **@rxliuli Please run `npm install` to bring it up to date with the changes in `package.json`**

It has been modified. In addition, I merged the upstream modification (ie the latest commit of this repository) and resolved the conflict.

**Review by fussel178 — APPROVED** [review]
LGTM. Thank you for your contribution! :smile:

**Review by pklaschka — APPROVED** [review]
LGTM, I'll go ahead and merge it 🙂 

Thank you very much for your contribution.

**Pull request merged**
